version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:13
    container_name: pacs_postgres
    environment:
      POSTGRES_DB: orthanc
      POSTGRES_USER: orthanc
      POSTGRES_PASSWORD: orthanc
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pacs_internal_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orthanc -d orthanc"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Orthanc PACS server
  orthanc_server:
    image: jodogne/orthanc-plugins:latest
    container_name: pacs_orthanc_server
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8042:8042"
      - "4242:4242"
    volumes:
      - orthanc_data:/var/lib/orthanc/db
      - ./config/orthanc:/etc/orthanc:ro
    networks:
      - pacs_internal_net
    restart: unless-stopped
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: orthanc
      POSTGRES_USER: orthanc
      POSTGRES_PASSWORD: orthanc

  # OHIF Viewer with Supabase (simplified)
  ohif_viewer:
    image: ohif/viewer:latest
    container_name: pacs_ohif_supabase
    networks:
      - pacs_internal_net
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  # Nginx Proxy
  nginx_proxy:
    image: nginx:alpine
    container_name: pacs_nginx_supabase
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/nginx.supabase.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html/static:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
    depends_on:
      - ohif_viewer
      - orthanc_server
    networks:
      - pacs_internal_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  orthanc_data:

networks:
  pacs_internal_net:
    driver: bridge 